services:
  postgres:
    container_name: postgres-sql-network
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: deneme_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-network
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  steamescrow-api:
    container_name: steamescrow-api
    image: molfiks/deneme:1.0.2
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  steamescrow-ui:
    container_name: steamescrow-ui
    image: molfiks/deneme-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - steamescrow-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local

# test