/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBoughtProductResponse } from '../../models/page-response-bought-product-response';

export interface FindAllSoldProducts$Params {
  page?: number;
  size?: number;
}

export function findAllSoldProducts(http: HttpClient, rootUrl: string, params?: FindAllSoldProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBoughtProductResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllSoldProducts.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBoughtProductResponse>;
    })
  );
}

findAllSoldProducts.PATH = '/products/sold';
