/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BoughtProductResponse {
  id?: number;
  price?: number;
  purchaseApproved?: boolean;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
  sellerName?: string;
  title?: string;
}
