/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductResponse } from '../models/product-response';
export interface FavoritesResponse {
  addedDate?: string;
  id?: number;
  productResponse: ProductResponse;
}
