/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BoughtProductResponse } from '../models/bought-product-response';
export interface PageResponseBoughtProductResponse {
  content?: Array<BoughtProductResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
