/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductRequest {
  authorName: string;
  description: string;
  id?: number;
  shareable?: boolean;
  title: string;
}
