/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  archived?: boolean;
  authorName?: string;
  cover?: string;
  description?: string;
  id?: number;
  owner?: string;
  rate?: number;
  shareable?: boolean;
  title?: string;
  bought?: boolean;
  boughtBy?: string;
}
