/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approvePurchaseProduct } from '../fn/product/approve-purchase-product';
import { ApprovePurchaseProduct$Params } from '../fn/product/approve-purchase-product';
import { findAllBoughtProducts } from '../fn/product/find-all-bought-products';
import { FindAllBoughtProducts$Params } from '../fn/product/find-all-bought-products';
import { findAllProducts } from '../fn/product/find-all-products';
import { FindAllProducts$Params } from '../fn/product/find-all-products';
import { findAllProductsByOwner } from '../fn/product/find-all-products-by-owner';
import { FindAllProductsByOwner$Params } from '../fn/product/find-all-products-by-owner';
import { findAllReturnedProducts } from '../fn/product/find-all-returned-products';
import { FindAllReturnedProducts$Params } from '../fn/product/find-all-returned-products';
import { findAllSoldProducts } from '../fn/product/find-all-sold-products';
import { FindAllSoldProducts$Params } from '../fn/product/find-all-sold-products';
import { findProductById } from '../fn/product/find-product-by-id';
import { FindProductById$Params } from '../fn/product/find-product-by-id';
import { getProductImages } from '../fn/product/get-product-images';
import { GetProductImages$Params } from '../fn/product/get-product-images';
import { PageResponseBoughtProductResponse } from '../models/page-response-bought-product-response';
import { PageResponseProductResponse } from '../models/page-response-product-response';
import { ProductResponse } from '../models/product-response';
import { purchaseProduct } from '../fn/product/purchase-product';
import { PurchaseProduct$Params } from '../fn/product/purchase-product';
import { saveProduct } from '../fn/product/save-product';
import { SaveProduct$Params } from '../fn/product/save-product';
import { updateArchivedStatus } from '../fn/product/update-archived-status';
import { UpdateArchivedStatus$Params } from '../fn/product/update-archived-status';
import { updateShareableStatus } from '../fn/product/update-shareable-status';
import { UpdateShareableStatus$Params } from '../fn/product/update-shareable-status';
import { uploadProductCoverPicture } from '../fn/product/upload-product-cover-picture';
import { UploadProductCoverPicture$Params } from '../fn/product/upload-product-cover-picture';
import { uploadProductImages } from '../fn/product/upload-product-images';
import { UploadProductImages$Params } from '../fn/product/upload-product-images';

@Injectable({ providedIn: 'root' })
export class ProductService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllProducts()` */
  static readonly FindAllProductsPath = '/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllProducts$Response(params?: FindAllProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProductResponse>> {
    return findAllProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllProducts(params?: FindAllProducts$Params, context?: HttpContext): Observable<PageResponseProductResponse> {
    return this.findAllProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseProductResponse>): PageResponseProductResponse => r.body)
    );
  }

  /** Path part for operation `saveProduct()` */
  static readonly SaveProductPath = '/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveProduct()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveProduct$Response(params: SaveProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveProduct$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveProduct(params: SaveProduct$Params, context?: HttpContext): Observable<number> {
    return this.saveProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `purchaseProduct()` */
  static readonly PurchaseProductPath = '/products/purchase/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purchaseProduct()` instead.
   *
   * This method doesn't expect any request body.
   */
  purchaseProduct$Response(params: PurchaseProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return purchaseProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purchaseProduct$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  purchaseProduct(params: PurchaseProduct$Params, context?: HttpContext): Observable<number> {
    return this.purchaseProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getProductImages()` */
  static readonly GetProductImagesPath = '/products/images/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductImages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductImages$Response(params: GetProductImages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return getProductImages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductImages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductImages(params: GetProductImages$Params, context?: HttpContext): Observable<Array<string>> {
    return this.getProductImages$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `uploadProductImages()` */
  static readonly UploadProductImagesPath = '/products/images/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadProductImages()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProductImages$Response(params: UploadProductImages$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadProductImages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadProductImages$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProductImages(params: UploadProductImages$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadProductImages$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `uploadProductCoverPicture()` */
  static readonly UploadProductCoverPicturePath = '/products/cover/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadProductCoverPicture()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProductCoverPicture$Response(params: UploadProductCoverPicture$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadProductCoverPicture(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadProductCoverPicture$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProductCoverPicture(params: UploadProductCoverPicture$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadProductCoverPicture$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `updateShareableStatus()` */
  static readonly UpdateShareableStatusPath = '/products/shareable/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateShareableStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateShareableStatus$Response(params: UpdateShareableStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateShareableStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateShareableStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateShareableStatus(params: UpdateShareableStatus$Params, context?: HttpContext): Observable<number> {
    return this.updateShareableStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `approvePurchaseProduct()` */
  static readonly ApprovePurchaseProductPath = '/products/purchase/approve/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approvePurchaseProduct()` instead.
   *
   * This method doesn't expect any request body.
   */
  approvePurchaseProduct$Response(params: ApprovePurchaseProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return approvePurchaseProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approvePurchaseProduct$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approvePurchaseProduct(params: ApprovePurchaseProduct$Params, context?: HttpContext): Observable<number> {
    return this.approvePurchaseProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateArchivedStatus()` */
  static readonly UpdateArchivedStatusPath = '/products/archived/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateArchivedStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateArchivedStatus$Response(params: UpdateArchivedStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateArchivedStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateArchivedStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateArchivedStatus(params: UpdateArchivedStatus$Params, context?: HttpContext): Observable<number> {
    return this.updateArchivedStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findProductById()` */
  static readonly FindProductByIdPath = '/products/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findProductById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findProductById$Response(params: FindProductById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return findProductById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findProductById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findProductById(params: FindProductById$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.findProductById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `findAllSoldProducts()` */
  static readonly FindAllSoldProductsPath = '/products/sold';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllSoldProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllSoldProducts$Response(params?: FindAllSoldProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBoughtProductResponse>> {
    return findAllSoldProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllSoldProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllSoldProducts(params?: FindAllSoldProducts$Params, context?: HttpContext): Observable<PageResponseBoughtProductResponse> {
    return this.findAllSoldProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBoughtProductResponse>): PageResponseBoughtProductResponse => r.body)
    );
  }

  /** Path part for operation `findAllReturnedProducts()` */
  static readonly FindAllReturnedProductsPath = '/products/returned';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllReturnedProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedProducts$Response(params?: FindAllReturnedProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBoughtProductResponse>> {
    return findAllReturnedProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllReturnedProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedProducts(params?: FindAllReturnedProducts$Params, context?: HttpContext): Observable<PageResponseBoughtProductResponse> {
    return this.findAllReturnedProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBoughtProductResponse>): PageResponseBoughtProductResponse => r.body)
    );
  }

  /** Path part for operation `findAllProductsByOwner()` */
  static readonly FindAllProductsByOwnerPath = '/products/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllProductsByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllProductsByOwner$Response(params?: FindAllProductsByOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProductResponse>> {
    return findAllProductsByOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllProductsByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllProductsByOwner(params?: FindAllProductsByOwner$Params, context?: HttpContext): Observable<PageResponseProductResponse> {
    return this.findAllProductsByOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseProductResponse>): PageResponseProductResponse => r.body)
    );
  }

  /** Path part for operation `findAllBoughtProducts()` */
  static readonly FindAllBoughtProductsPath = '/products/bought';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBoughtProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBoughtProducts$Response(params?: FindAllBoughtProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBoughtProductResponse>> {
    return findAllBoughtProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBoughtProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBoughtProducts(params?: FindAllBoughtProducts$Params, context?: HttpContext): Observable<PageResponseBoughtProductResponse> {
    return this.findAllBoughtProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBoughtProductResponse>): PageResponseBoughtProductResponse => r.body)
    );
  }

}
